dist: trusty
sudo: false
addons:
    apt:
        packages:
            - google-chrome-stable
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start &
    - sleep 3
    - npm install -g phantomjs-prebuilt; npm install -g protractor@5.1.2; webdriver-manager update
script: "sh ./runtest.sh"
language: node_js
node_js: 
    - "6.3.0"